[2022-03-08 14:35:54,095][Thread-1:18644][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 17, in index
    logger.info(str(RedisConnection.get('hotarticle').__dict__))
AttributeError: 'bytes' object has no attribute '__dict__'
[2022-03-08 14:36:51,149][Thread-1:21320][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 17, in index
    logger.info(str(RedisConnection.get('hotarticle').encode("utf-8")))
AttributeError: 'bytes' object has no attribute 'encode'
[2022-03-08 14:37:03,417][Thread-1:3244][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 17, in index
    logger.info(str(RedisConnection.get('hotarticle').decode("utf-8")))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
[2022-03-08 22:40:22,061][Thread-1:3296][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 15, in index
    RedisConnection = get_redis_connection('default')
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django_redis\__init__.py", line 15, in get_redis_connection
    raise NotImplementedError("This backend does not support this feature")
NotImplementedError: This backend does not support this feature
[2022-03-08 22:43:16,993][Thread-1:13416][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 16, in index
    logger.info(len(pickle.loads(get_redis_connection('default').get('hotarticle'))))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django_redis\__init__.py", line 15, in get_redis_connection
    raise NotImplementedError("This backend does not support this feature")
NotImplementedError: This backend does not support this feature
[2022-03-08 22:45:01,921][Thread-1:13416][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 16, in index
    logger.info(len(pickle.loads(get_redis_connection('default').get('hotarticle'))))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django_redis\__init__.py", line 15, in get_redis_connection
    raise NotImplementedError("This backend does not support this feature")
NotImplementedError: This backend does not support this feature
[2022-03-08 22:47:42,463][Thread-1:12748][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 16, in index
    logger.info(len(pickle.loads(get_redis_connection('default').get('hotarticle'))))
TypeError: a bytes-like object is required, not 'NoneType'
[2022-03-08 22:47:43,470][Thread-1:12748][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 16, in index
    logger.info(len(pickle.loads(get_redis_connection('default').get('hotarticle'))))
TypeError: a bytes-like object is required, not 'NoneType'
[2022-03-08 22:47:44,213][Thread-1:12748][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 16, in index
    logger.info(len(pickle.loads(get_redis_connection('default').get('hotarticle'))))
TypeError: a bytes-like object is required, not 'NoneType'
[2022-03-09 20:42:37,658][Thread-1:18732][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
TypeError: 'FileSystemFinder' object is not callable
[2022-03-10 18:38:40,638][Thread-3:26960][task_id:django.request][log.py:222][ERROR][Internal Server Error: /admin/mysite/article/add/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 992, in render
    return render_value_in_context(output, context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 971, in render_value_in_context
    value = str(value)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\html.py", line 373, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 33, in __str__
    return self.as_widget()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 92, in as_widget
    return widget.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\ckeditor\widgets.py", line 114, in render
    renderer.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 30, in render
    template = self.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 36, in get_template
    return self.engine.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 36, in get_template
    reraise(exc, self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html
[2022-03-10 18:40:44,576][Thread-2:9972][task_id:django.request][log.py:222][ERROR][Internal Server Error: /admin/mysite/article/add/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 992, in render
    return render_value_in_context(output, context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 971, in render_value_in_context
    value = str(value)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\html.py", line 373, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 33, in __str__
    return self.as_widget()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 92, in as_widget
    return widget.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\ckeditor\widgets.py", line 114, in render
    renderer.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 30, in render
    template = self.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 36, in get_template
    return self.engine.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 36, in get_template
    reraise(exc, self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html
[2022-03-10 18:48:24,525][Thread-1:20872][task_id:django.request][log.py:222][ERROR][Internal Server Error: /admin/mysite/article/add/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 992, in render
    return render_value_in_context(output, context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 971, in render_value_in_context
    value = str(value)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\html.py", line 373, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 33, in __str__
    return self.as_widget()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 92, in as_widget
    return widget.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\ckeditor\widgets.py", line 114, in render
    renderer.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 30, in render
    template = self.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 36, in get_template
    return self.engine.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 36, in get_template
    reraise(exc, self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html
[2022-03-10 19:05:36,568][Thread-4:24708][task_id:django.request][log.py:222][ERROR][Internal Server Error: /read/1/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 34, in read
    comments = TComment.objects.filter(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1354, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1381, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1254, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1486, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'article_id' into field. Choices are: body, child_comments, create, id, level, lft, parent, parent_id, reply_to, reply_to_id, rght, tree_id, user, user_id
[2022-03-10 19:05:52,556][Thread-4:24708][task_id:django.request][log.py:222][ERROR][Internal Server Error: /read/1/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 34, in read
    comments = TComment.objects.filter(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1354, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1381, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1254, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1486, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'article_id' into field. Choices are: body, child_comments, create, id, level, lft, parent, parent_id, reply_to, reply_to_id, rght, tree_id, user, user_id
[2022-03-10 19:11:43,084][Thread-1:16036][task_id:django.request][log.py:222][ERROR][Internal Server Error: /comment/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\django_blog-master\django_blog-master\comment\views.py", line 15, in comment
    models.Comment.objects.create(article_id=article_id, parent_id=parent, reply_to_id=reply_to, user_id=user,
AttributeError: module 'comment.models' has no attribute 'Comment'
